# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ahmednaggar19/OS/Shell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ahmednaggar19/OS/Shell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ahmednaggar19/OS/Shell/CMakeFiles /home/ahmednaggar19/OS/Shell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ahmednaggar19/OS/Shell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shell

# Build rule for target.
shell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shell
.PHONY : shell

# fast build rule for target.
shell/fast:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/build
.PHONY : shell/fast

environment/Environment.o: environment/Environment.c.o

.PHONY : environment/Environment.o

# target to build an object file
environment/Environment.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/environment/Environment.c.o
.PHONY : environment/Environment.c.o

environment/Environment.i: environment/Environment.c.i

.PHONY : environment/Environment.i

# target to preprocess a source file
environment/Environment.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/environment/Environment.c.i
.PHONY : environment/Environment.c.i

environment/Environment.s: environment/Environment.c.s

.PHONY : environment/Environment.s

# target to generate assembly for a file
environment/Environment.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/environment/Environment.c.s
.PHONY : environment/Environment.c.s

environment/Variables.o: environment/Variables.c.o

.PHONY : environment/Variables.o

# target to build an object file
environment/Variables.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/environment/Variables.c.o
.PHONY : environment/Variables.c.o

environment/Variables.i: environment/Variables.c.i

.PHONY : environment/Variables.i

# target to preprocess a source file
environment/Variables.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/environment/Variables.c.i
.PHONY : environment/Variables.c.i

environment/Variables.s: environment/Variables.c.s

.PHONY : environment/Variables.s

# target to generate assembly for a file
environment/Variables.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/environment/Variables.c.s
.PHONY : environment/Variables.c.s

executers/BatchExecuter.o: executers/BatchExecuter.c.o

.PHONY : executers/BatchExecuter.o

# target to build an object file
executers/BatchExecuter.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/BatchExecuter.c.o
.PHONY : executers/BatchExecuter.c.o

executers/BatchExecuter.i: executers/BatchExecuter.c.i

.PHONY : executers/BatchExecuter.i

# target to preprocess a source file
executers/BatchExecuter.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/BatchExecuter.c.i
.PHONY : executers/BatchExecuter.c.i

executers/BatchExecuter.s: executers/BatchExecuter.c.s

.PHONY : executers/BatchExecuter.s

# target to generate assembly for a file
executers/BatchExecuter.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/BatchExecuter.c.s
.PHONY : executers/BatchExecuter.c.s

executers/CommandExecuter.o: executers/CommandExecuter.c.o

.PHONY : executers/CommandExecuter.o

# target to build an object file
executers/CommandExecuter.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/CommandExecuter.c.o
.PHONY : executers/CommandExecuter.c.o

executers/CommandExecuter.i: executers/CommandExecuter.c.i

.PHONY : executers/CommandExecuter.i

# target to preprocess a source file
executers/CommandExecuter.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/CommandExecuter.c.i
.PHONY : executers/CommandExecuter.c.i

executers/CommandExecuter.s: executers/CommandExecuter.c.s

.PHONY : executers/CommandExecuter.s

# target to generate assembly for a file
executers/CommandExecuter.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/CommandExecuter.c.s
.PHONY : executers/CommandExecuter.c.s

executers/InteractiveExecuter.o: executers/InteractiveExecuter.c.o

.PHONY : executers/InteractiveExecuter.o

# target to build an object file
executers/InteractiveExecuter.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/InteractiveExecuter.c.o
.PHONY : executers/InteractiveExecuter.c.o

executers/InteractiveExecuter.i: executers/InteractiveExecuter.c.i

.PHONY : executers/InteractiveExecuter.i

# target to preprocess a source file
executers/InteractiveExecuter.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/InteractiveExecuter.c.i
.PHONY : executers/InteractiveExecuter.c.i

executers/InteractiveExecuter.s: executers/InteractiveExecuter.c.s

.PHONY : executers/InteractiveExecuter.s

# target to generate assembly for a file
executers/InteractiveExecuter.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/InteractiveExecuter.c.s
.PHONY : executers/InteractiveExecuter.c.s

executers/RegisteredCommands.o: executers/RegisteredCommands.c.o

.PHONY : executers/RegisteredCommands.o

# target to build an object file
executers/RegisteredCommands.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/RegisteredCommands.c.o
.PHONY : executers/RegisteredCommands.c.o

executers/RegisteredCommands.i: executers/RegisteredCommands.c.i

.PHONY : executers/RegisteredCommands.i

# target to preprocess a source file
executers/RegisteredCommands.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/RegisteredCommands.c.i
.PHONY : executers/RegisteredCommands.c.i

executers/RegisteredCommands.s: executers/RegisteredCommands.c.s

.PHONY : executers/RegisteredCommands.s

# target to generate assembly for a file
executers/RegisteredCommands.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/executers/RegisteredCommands.c.s
.PHONY : executers/RegisteredCommands.c.s

file_handlers/FileReader.o: file_handlers/FileReader.c.o

.PHONY : file_handlers/FileReader.o

# target to build an object file
file_handlers/FileReader.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/file_handlers/FileReader.c.o
.PHONY : file_handlers/FileReader.c.o

file_handlers/FileReader.i: file_handlers/FileReader.c.i

.PHONY : file_handlers/FileReader.i

# target to preprocess a source file
file_handlers/FileReader.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/file_handlers/FileReader.c.i
.PHONY : file_handlers/FileReader.c.i

file_handlers/FileReader.s: file_handlers/FileReader.c.s

.PHONY : file_handlers/FileReader.s

# target to generate assembly for a file
file_handlers/FileReader.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/file_handlers/FileReader.c.s
.PHONY : file_handlers/FileReader.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/main.c.s
.PHONY : main.c.s

parser/CommandNormalizer.o: parser/CommandNormalizer.c.o

.PHONY : parser/CommandNormalizer.o

# target to build an object file
parser/CommandNormalizer.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/parser/CommandNormalizer.c.o
.PHONY : parser/CommandNormalizer.c.o

parser/CommandNormalizer.i: parser/CommandNormalizer.c.i

.PHONY : parser/CommandNormalizer.i

# target to preprocess a source file
parser/CommandNormalizer.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/parser/CommandNormalizer.c.i
.PHONY : parser/CommandNormalizer.c.i

parser/CommandNormalizer.s: parser/CommandNormalizer.c.s

.PHONY : parser/CommandNormalizer.s

# target to generate assembly for a file
parser/CommandNormalizer.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/parser/CommandNormalizer.c.s
.PHONY : parser/CommandNormalizer.c.s

parser/Parser.o: parser/Parser.c.o

.PHONY : parser/Parser.o

# target to build an object file
parser/Parser.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/parser/Parser.c.o
.PHONY : parser/Parser.c.o

parser/Parser.i: parser/Parser.c.i

.PHONY : parser/Parser.i

# target to preprocess a source file
parser/Parser.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/parser/Parser.c.i
.PHONY : parser/Parser.c.i

parser/Parser.s: parser/Parser.c.s

.PHONY : parser/Parser.s

# target to generate assembly for a file
parser/Parser.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/parser/Parser.c.s
.PHONY : parser/Parser.c.s

utils/Constants.o: utils/Constants.c.o

.PHONY : utils/Constants.o

# target to build an object file
utils/Constants.c.o:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/utils/Constants.c.o
.PHONY : utils/Constants.c.o

utils/Constants.i: utils/Constants.c.i

.PHONY : utils/Constants.i

# target to preprocess a source file
utils/Constants.c.i:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/utils/Constants.c.i
.PHONY : utils/Constants.c.i

utils/Constants.s: utils/Constants.c.s

.PHONY : utils/Constants.s

# target to generate assembly for a file
utils/Constants.c.s:
	$(MAKE) -f CMakeFiles/shell.dir/build.make CMakeFiles/shell.dir/utils/Constants.c.s
.PHONY : utils/Constants.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shell"
	@echo "... environment/Environment.o"
	@echo "... environment/Environment.i"
	@echo "... environment/Environment.s"
	@echo "... environment/Variables.o"
	@echo "... environment/Variables.i"
	@echo "... environment/Variables.s"
	@echo "... executers/BatchExecuter.o"
	@echo "... executers/BatchExecuter.i"
	@echo "... executers/BatchExecuter.s"
	@echo "... executers/CommandExecuter.o"
	@echo "... executers/CommandExecuter.i"
	@echo "... executers/CommandExecuter.s"
	@echo "... executers/InteractiveExecuter.o"
	@echo "... executers/InteractiveExecuter.i"
	@echo "... executers/InteractiveExecuter.s"
	@echo "... executers/RegisteredCommands.o"
	@echo "... executers/RegisteredCommands.i"
	@echo "... executers/RegisteredCommands.s"
	@echo "... file_handlers/FileReader.o"
	@echo "... file_handlers/FileReader.i"
	@echo "... file_handlers/FileReader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser/CommandNormalizer.o"
	@echo "... parser/CommandNormalizer.i"
	@echo "... parser/CommandNormalizer.s"
	@echo "... parser/Parser.o"
	@echo "... parser/Parser.i"
	@echo "... parser/Parser.s"
	@echo "... utils/Constants.o"
	@echo "... utils/Constants.i"
	@echo "... utils/Constants.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

